const LOGIN = "LOGIN";
const LOGIN_ACK = "LOGIN_ACK";
const SIGNUP = "SIGNUP";
const SIGNUP_ACK = "SIGNUP_ACK";
const START_CHAT = "START_CHAT";
export { LOGIN, LOGIN_ACK, SIGNUP, SIGNUP_ACK, START_CHAT };
